### ISSUE TITLE
make gif animation from gibs data

### ISSUE THREAD

**Issue by hyzhak** [botstory/nasa-bot#6]
# TODO
- [x] download image sequence
- [x] squeeze sequence to gif animation
- [x] remove raw images sequence

# could use
- [x] https://github.com/imageio/imageio
- [x] https://github.com/dahlia/wand - ImageMagick binding - 40% slower 👎 

# performance

### imageoio
```
duration: 0:00:38.991241
- download: 0:00:08.149760
- animation: 0:00:30.814000
- remove: 0:00:00.027481
```
### wand
```
# duration: 0:00:48.437090
# - download: 0:00:08.104954
# - animation: 0:00:40.304403
# - remove: 0:00:00.027733
```
### imageoio
```
duration: 0:00:05.053599
- download: 0:00:02.751033
- animation: 0:00:02.297507
- remove: 0:00:00.005059
```
### wand
```
duration: 0:00:06.067059
- download: 0:00:02.736638
- animation: 0:00:03.324310
- remove: 0:00:00.006111
```
### imageoio
```
duration: 0:00:02.176394
- download: 0:00:01.584750
- animation: 0:00:00.591166
- remove: 0:00:00.000478
```
### wand
```
duration: 0:00:02.653051
- download: 0:00:01.802514
- animation: 0:00:00.850057
- remove: 0:00:00.000480
```
